Fix webpack issues by using a workaround
The workaround is described in https://github.com/webpack/webpack/issues/7352
Note that now the webserver cannot load our wasm:
"TypeError: _myelin_visualization_bg__WEBPACK_IMPORTED_MODULE_0__.init is not a function"
This might be caused by a transcient dependency on stdweb:
https://github.com/sebcrozet/nphysics/blob/master/build/nphysics2d/Cargo.toml#L31
Which is incompatible with wasm-bindgen:
https://github.com/koute/stdweb/issues/263